GET http://localhost:8080/user/product HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTk2MjMzMDQzfQ.6p3vUYdWHw1xtch9XDq6nUy6zwQzA_bSpOfDiKuwOys

###

POST http://localhost:8080/user/product?id=3 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTk2MjMzMDQzfQ.6p3vUYdWHw1xtch9XDq6nUy6zwQzA_bSpOfDiKuwOys

###

DELETE http://localhost:8080/user/product?id=3 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTk2MjMzMDQzfQ.6p3vUYdWHw1xtch9XDq6nUy6zwQzA_bSpOfDiKuwOys

###

GET http://localhost:8080/user/product/favorite HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTk2MjMzMDQzfQ.6p3vUYdWHw1xtch9XDq6nUy6zwQzA_bSpOfDiKuwOys

###

POST http://localhost:8080/user/product/favorite?id=3 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTk2MjMzMDQzfQ.6p3vUYdWHw1xtch9XDq6nUy6zwQzA_bSpOfDiKuwOys

###

DELETE http://localhost:8080/user/product/favorite?id=3 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTk2MjMzMDQzfQ.6p3vUYdWHw1xtch9XDq6nUy6zwQzA_bSpOfDiKuwOys